[toolbox]
network = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
rate_limiter = "Brg18kjrWYWA7rQvabRmGQDChf7d844T2NeVkaPSykwd"

[programs.devnet]
rate_limiter = "Brg18kjrWYWA7rQvabRmGQDChf7d844T2NeVkaPSykwd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.30.0"
